version: '3'
services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres'
    restart: always
    volumes:
      - 'nfsmountdbdata:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=MEXICO123
      - PGDATA=/var/lib/postgresql/data/pgdata
    user: 1000:1000
    ports:
      - '5432:5432'
volumes:
  nfsmountdbdata:
    external: true